require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const User = require('../src/models/userModel');
const { CV_UPLOAD_DIR } = require('../src/middleware/uploadMiddleware');

// Builds a minimal but genuinely valid one-page PDF so the Admin "View CV"
// feature has a real file to open. Offsets are computed as the body is
// assembled, because a PDF xref table must point at exact byte positions.
const buildPlaceholderCV = (name, position) => {
    const text = (s) => s.replace(/([\\()])/g, '\\$1');
    const content =
        `BT /F1 22 Tf 72 760 Td (${text(name)}) Tj ET\n` +
        `BT /F1 13 Tf 72 735 Td (${text(position || 'Waveskill Employee')}) Tj ET\n` +
        `BT /F1 11 Tf 72 700 Td (Placeholder CV generated by scripts/seedUsers.js) Tj ET\n` +
        `BT /F1 11 Tf 72 682 Td (Replace it by uploading a real CV from the Employee profile page.) Tj ET\n`;

    const objects = [
        '<</Type/Catalog/Pages 2 0 R>>',
        '<</Type/Pages/Kids[3 0 R]/Count 1>>',
        '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>',
        '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
        `<</Length ${content.length}>>\nstream\n${content}endstream`
    ];

    let pdf = '%PDF-1.4\n';
    const offsets = [];
    objects.forEach((body, i) => {
        offsets.push(pdf.length);
        pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefStart = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    offsets.forEach((off) => {
        pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
    });
    pdf += `trailer\n<</Size ${objects.length + 1}/Root 1 0 R>>\nstartxref\n${xrefStart}\n%%EOF\n`;

    return Buffer.from(pdf, 'latin1');
};

// Writes the placeholder CV to the same folder real uploads land in, and
// returns the stored filename (matching what uploadCV persists).
const writePlaceholderCV = (user) => {
    const filename = `seed-cv-${user.email.split('@')[0]}.pdf`;
    fs.mkdirSync(CV_UPLOAD_DIR, { recursive: true });
    fs.writeFileSync(path.join(CV_UPLOAD_DIR, filename), buildPlaceholderCV(user.name, user.position));
    return filename;
};

const DEMO_USERS = [
    {
        name: 'Sarah Manager',
        email: 'manager@waveskill.com',
        password: 'Manager@123',
        role: 'Manager',
        department: 'Engineering',
        position: 'Engineering Manager',
        employeeId: 'EMP-000002',
        phoneNumber: '+94 77 111 1111',
        maritalStatus: 'Married',
        cvUpdateStatus: 'Up to Date',
    },
    {
        name: 'John Doe',
        email: 'john@waveskill.com',
        password: 'Demo@1234',
        role: 'Employee',
        department: 'Engineering',
        position: 'Software Engineer',
        employeeId: 'EMP-000003',
        phoneNumber: '+94 77 222 2222',
        maritalStatus: 'Single',
        cvUpdateStatus: 'Up to Date',
    },
    {
        name: 'Jane Smith',
        email: 'jane@waveskill.com',
        password: 'Demo@1234',
        role: 'Employee',
        department: 'Marketing',
        position: 'Marketing Specialist',
        employeeId: 'EMP-000004',
        phoneNumber: '+94 77 333 3333',
        maritalStatus: 'Married',
        cvUpdateStatus: 'Pending Review',
    },
    {
        name: 'Mike Johnson',
        email: 'mike@waveskill.com',
        password: 'Demo@1234',
        role: 'Employee',
        department: 'Engineering',
        position: 'QA Engineer',
        employeeId: 'EMP-000005',
        phoneNumber: '+94 77 444 4444',
        maritalStatus: 'Divorced',
        cvUpdateStatus: 'Needs Update',
    },
    {
        name: 'Lisa Chen',
        email: 'lisa@waveskill.com',
        password: 'Demo@1234',
        role: 'Employee',
        department: 'Human Resources',
        position: 'HR Coordinator',
        employeeId: 'EMP-000006',
        phoneNumber: '+94 77 555 5555',
        maritalStatus: 'Widowed',
        cvUpdateStatus: 'Up to Date',
    },
    {
        // Seeded as a former employee so the Admin employee tab has something
        // to show under the "Inactive" filter and the Reactivate button is
        // exercisable straight after seeding.
        name: 'Ravi Fernando',
        email: 'ravi@waveskill.com',
        password: 'Demo@1234',
        role: 'Employee',
        department: 'Sales',
        position: 'Sales Executive',
        employeeId: 'EMP-000007',
        phoneNumber: '+94 77 666 6666',
        maritalStatus: 'Married',
        cvUpdateStatus: 'Needs Update',
        status: 'Inactive',
        deactivatedAt: new Date(),
    },
];

(async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);

        // One-time migration for accounts created before `status` existed.
        // This has to be a raw updateMany: loading such a document through the
        // model applies the schema default in memory, so a doc.status check
        // always looks populated and would never write the field to disk.
        const migrated = await User.collection.updateMany(
            { status: { $exists: false } },
            { $set: { status: 'Active' } }
        );
        if (migrated.modifiedCount) {
            console.log(`Backfilled status='Active' on ${migrated.modifiedCount} pre-existing account(s)`);
        }

        let created = 0;
        let backfilled = 0;
        let unchanged = 0;

        for (const u of DEMO_USERS) {
            const existing = await User.findOne({ email: u.email });

            if (!existing) {
                const user = await User.create(u);
                // Only employees/managers get a demo CV, matching cvUpdateStatus.
                if (u.cvUpdateStatus !== 'Needs Update') {
                    user.cvFile = writePlaceholderCV(user);
                    await user.save();
                }
                created++;
                continue;
            }

            // The original seeder skipped anyone who already existed, which left
            // previously-seeded accounts without a marital status forever. Fill
            // in the new fields on existing records instead of skipping them.
            let changed = false;

            if (!existing.maritalStatus) {
                existing.maritalStatus = u.maritalStatus;
                changed = true;
            }
            if (u.cvUpdateStatus !== 'Needs Update' && !existing.cvFile) {
                existing.cvFile = writePlaceholderCV(existing);
                existing.cvUpdateStatus = u.cvUpdateStatus;
                changed = true;
            }
            if (changed) {
                await existing.save();
                backfilled++;
            } else {
                unchanged++;
            }
        }

        console.log(`Users seeded: ${created} created, ${backfilled} backfilled, ${unchanged} already up to date`);
        console.log('Default password for demo employees: Demo@1234');
        console.log('Manager password: Manager@123');
        process.exit(0);
    } catch (e) {
        console.error(`Seed users failed: ${e.message}`);
        process.exit(1);
    }
})();
