const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const userSchema = new mongoose.Schema({
    name: { type: String, required: [true, 'Please add a name'] },
    email: { type: String, required: [true, 'Please add an email'], unique: true },
    password: { type: String, required: [true, 'Please add a password'] },
    role: { type: String, enum: ['Employee', 'Manager', 'Admin', 'Customer'], default: 'Employee' },

    // Accounts are deactivated rather than deleted, so history (attendance,
    // leaves, OT) keeps resolving. Documents created before this field existed
    // have no value, so queries must treat "missing" as Active.
    status: { type: String, enum: ['Active', 'Inactive'], default: 'Active' },
    deactivatedAt: { type: Date },
    deactivatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

    department: { type: String, default: 'Unassigned' },
    position: { type: String, default: 'Employee' },
    employeeId: { type: String },
    
    // [LEARNING NOTE]: Standard 3-line address format for professional HR systems
    addressLine1: { type: String },
    addressLine2: { type: String },
    addressLine3: { type: String },
    
    countryCode: { type: String, default: '+94' }, 
    phoneNumber: { type: String }, 
    
    // [LEARNING NOTE]: profilePhoto will store the Base64 image string generated by our cropper
    profilePhoto: { type: String }, 
    cvFile: { type: String },
    
    joinDate: { type: Date, default: Date.now },
    totalAnnualLeave: { type: Number, default: 35 }, 
    
    emergencyContact: {
        name: { type: String },
        countryCode: { type: String, default: '+94' },
        phone: { type: String },
        relation: { type: String } 
    },
    
    medicalDetails: {
        bloodGroup: { type: String },
        allergies: { type: String, default: 'None' },
        conditions: { type: String, default: 'None' } 
    },
    
    skills: [{
        name: { type: String },
        level: { type: String, enum: ['Beginner', 'Intermediate', 'Advanced', 'Expert'] },
        percentage: { type: Number }
    }],
    
    // [LEARNING NOTE]: This array acts as a historical log. Newest items go to the top.
    activities: [{
        action: { type: String },
        date: { type: Date, default: Date.now }
    }],
    
    maritalStatus: {
        type: String,
        enum: ['Single', 'Married', 'Divorced', 'Widowed']
    },
    
    cvUpdateStatus: {
        type: String,
        enum: ['Up to Date', 'Needs Update', 'Pending Review'],
        default: 'Needs Update'
    }
}, { timestamps: true });

// [LEARNING NOTE]: Automatically hashes the password before saving a new user to the DB
userSchema.pre('save', async function() {
    if (!this.isModified('password')) return; 
    const salt = await bcrypt.genSalt(10);
    this.password = await bcrypt.hash(this.password, salt);
});

// Used during login to verify the password
userSchema.methods.matchPassword = async function(enteredPassword) {
    return await bcrypt.compare(enteredPassword, this.password);
};

module.exports = mongoose.model('User', userSchema);